### PR TITLE
Update Home Screen UI

### PR DESCRIPTION
**Pull request by mahanvyakti**
The changes include:

1.  Home Screen interface update, 
2.  Minor changes in buttons on Login Screen
3.  Fixing the HTTP request issue to get temperature data

### CODE REVIEW

**Comment by shantanugodbole** [comment]
please confirm if app is working, changes are approved based on that condition @mahanvyakti 👍

**Comment by mahanvyakti** [comment]
The app is working perfectly fine @shantanugodbole

**Comment by shantanugodbole** [comment]
You can merge the request, great work 👍

**Review by shantanugodbole — APPROVED** [review]
Done

**Pull request merged**
